# Generated by Django 5.2.2 on 2025-06-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='АдресДоставки',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('страна', models.CharField(max_length=100)),
                ('город', models.CharField(max_length=100)),
                ('улица', models.CharField(max_length=200)),
                ('дом', models.CharField(max_length=20)),
                ('квартира', models.CharField(blank=True, max_length=20)),
                ('почтовый_индекс', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
        migrations.CreateModel(
            name='Категория',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Материал',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('описание', models.TextField()),
                ('экологичный', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Поставщик',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('контактное_лицо', models.CharField(max_length=100)),
                ('телефон', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Производитель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('страна', models.CharField(max_length=100)),
                ('сайт', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='СпособДоставки',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('стоимость', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
            },
        ),
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_заказа', models.DateTimeField(auto_now_add=True)),
                ('общая_сумма', models.DecimalField(decimal_places=2, max_digits=10)),
                ('адрес_доставки', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.адресдоставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='МатериалТовара',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('материал', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.материал')),
            ],
            options={
                'verbose_name': 'Материал товара',
                'verbose_name_plural': 'Материалы товаров',
            },
        ),
        migrations.CreateModel(
            name='Оплата',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('способ', models.CharField(max_length=50)),
                ('сумма', models.DecimalField(decimal_places=2, max_digits=10)),
                ('дата', models.DateTimeField(auto_now_add=True)),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Покупатель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('телефон', models.CharField(max_length=20)),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.AddField(
            model_name='заказ',
            name='покупатель',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.покупатель'),
        ),
        migrations.AddField(
            model_name='адресдоставки',
            name='покупатель',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.покупатель'),
        ),
        migrations.AddField(
            model_name='заказ',
            name='способ_доставки',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.способдоставки'),
        ),
        migrations.CreateModel(
            name='Товар',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200)),
                ('описание', models.TextField()),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('тип', models.CharField(max_length=50)),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.категория')),
                ('материалы', models.ManyToManyField(through='shop.МатериалТовара', to='shop.материал')),
                ('производитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Склад',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('размер', models.CharField(max_length=50)),
                ('цвет', models.CharField(max_length=50)),
                ('количество', models.IntegerField()),
                ('поставщик', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.поставщик')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.товар')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Скидка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('процент', models.IntegerField()),
                ('категория', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.категория')),
                ('товар', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Отзыв',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('оценка', models.IntegerField()),
                ('комментарий', models.TextField(blank=True)),
                ('дата', models.DateTimeField(auto_now_add=True)),
                ('покупатель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.покупатель')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='материалтовара',
            name='товар',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.товар'),
        ),
        migrations.CreateModel(
            name='ЭлементЗаказа',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.IntegerField()),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.заказ')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
