# Generated by Django 5.2.2 on 2025-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='товар',
            name='изображение',
            field=models.ImageField(blank=True, null=True, upload_to='товары/'),
        ),
    ]
